// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs3nOZHFgbnVuqZ8ijiDMJWrF6SSCyc_M',
    appId: '1:315165501732:web:22277618db7d5da2836bb1',
    messagingSenderId: '315165501732',
    projectId: 'beefit-4cdb8',
    authDomain: 'beefit-4cdb8.firebaseapp.com',
    storageBucket: 'beefit-4cdb8.appspot.com',
    measurementId: 'G-SMBS2KYWP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMw8lhBhR-_07xPmSBckQYpQg0VHFtm0M',
    appId: '1:315165501732:android:86e5969edf28c023836bb1',
    messagingSenderId: '315165501732',
    projectId: 'beefit-4cdb8',
    storageBucket: 'beefit-4cdb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2jlf0PJfO6iE3OQkXLjobP7k2oDJLOwA',
    appId: '1:315165501732:ios:93f3e0ca1670d743836bb1',
    messagingSenderId: '315165501732',
    projectId: 'beefit-4cdb8',
    storageBucket: 'beefit-4cdb8.appspot.com',
    iosBundleId: 'com.example.beefit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2jlf0PJfO6iE3OQkXLjobP7k2oDJLOwA',
    appId: '1:315165501732:ios:93f3e0ca1670d743836bb1',
    messagingSenderId: '315165501732',
    projectId: 'beefit-4cdb8',
    storageBucket: 'beefit-4cdb8.appspot.com',
    iosBundleId: 'com.example.beefit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs3nOZHFgbnVuqZ8ijiDMJWrF6SSCyc_M',
    appId: '1:315165501732:web:462741e08543fda2836bb1',
    messagingSenderId: '315165501732',
    projectId: 'beefit-4cdb8',
    authDomain: 'beefit-4cdb8.firebaseapp.com',
    storageBucket: 'beefit-4cdb8.appspot.com',
    measurementId: 'G-GEN8MFJM9D',
  );
}
